using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MMXOnline;

public partial class RPCCreateProj : RPC {
	public static Dictionary<int, ProjCreate> functs = new Dictionary<int, ProjCreate> {
		// X Stuff.
		//BUSTERS
		{ (int)ProjIds.Buster, BusterProj.rpcInvoke },
		{ (int)ProjIds.Buster2, Buster2Proj.rpcInvoke },
		{ (int)ProjIds.BusterUnpo, RagingBusterProj.rpcInvoke },
		{ (int)ProjIds.Buster3, Buster3LightProj.rpcInvoke },
		{ (int)ProjIds.Buster3Giga, Buster3GigaProj.rpcInvoke },
		{ (int)ProjIds.Buster3Max, Buster3MaxProj.rpcInvoke },
		{ (int)ProjIds.Buster4, Buster4Proj.rpcInvoke },
		{ (int)ProjIds.Buster4Giga, Buster4GigaProj.rpcInvoke },
		{ (int)ProjIds.Buster4Giga2, Buster4Giga2Proj.rpcInvoke },
		{ (int)ProjIds.Buster4Max, Buster4MaxProj.rpcInvoke },
		{ (int)ProjIds.BusterX3Proj2, BusterX3Proj2.rpcInvoke },
		{ (int)ProjIds.BusterX3Plasma, BusterPlasmaProj.rpcInvoke },
		{ (int)ProjIds.BusterX3PlasmaHit, BusterPlasmaHitProj.rpcInvoke },

		//X1 PROJS
		{ (int)ProjIds.Torpedo, TorpedoProjX.rpcInvoke },
		{ (int)ProjIds.TorpedoCharged, TorpedoProjChargedX.rpcInvoke },
		{ (int)ProjIds.Sting, StingProj.rpcInvoke },
		{ (int)ProjIds.StingDiag, StingProj.rpcInvoke },
		{ (int)ProjIds.RollingShield, RollingShieldProj.rpcInvoke },
		{ (int)ProjIds.RollingShieldCharged, RollingShieldProjCharged.rpcInvoke },
		{ (int)ProjIds.FireWave, FireWaveProj.rpcInvoke },
		{ (int)ProjIds.FireWaveChargedStart, FireWaveProjChargedStart.rpcInvoke },
		{ (int)ProjIds.FireWaveCharged, FireWaveProjCharged.rpcInvoke },
		{ (int)ProjIds.Tornado, TornadoProj.rpcInvoke },
		{ (int)ProjIds.TornadoCharged, TornadoProjCharged.rpcInvoke },
		{ (int)ProjIds.ElectricSpark, ElectricSparkProj.rpcInvoke },
		{ (int)ProjIds.ElectricSparkChargedStart, ElectricSparkProjChargedStart.rpcInvoke },
		{ (int)ProjIds.ElectricSparkCharged, ElectricSparkProjCharged.rpcInvoke },
		{ (int)ProjIds.Boomerang, BoomerangProj.rpcInvoke },
		{ (int)ProjIds.BoomerangCharged, BoomerangProjCharged.rpcInvoke },
		{ (int)ProjIds.ShotgunIce, ShotgunIceProj.rpcInvoke },
		{ (int)ProjIds.ShotgunIceCharged, ShotgunIceProjCharged.rpcInvoke },
		{ (int)ProjIds.ShotgunIceSled, ShotgunIceProjSled.rpcInvoke },
		{ (int)ProjIds.Hadouken, HadoukenProj.rpcInvoke} ,

		//X2 PROJS
		{ (int)ProjIds.CrystalHunter, CrystalHunterProj.rpcInvoke },
		{ (int)ProjIds.BubbleSplash, BubbleSplashProj.rpcInvoke },
		{ (int)ProjIds.BubbleSplashCharged, BubbleSplashProjCharged.rpcInvoke },
		{ (int)ProjIds.SilkShot, SilkShotProj.rpcInvoke },
		{ (int)ProjIds.SilkShotShrapnel, SilkShotProjShrapnel.rpcInvoke },
		{ (int)ProjIds.SilkShotChargedLv2, SilkShotProjLv2.rpcInvoke },
		{ (int)ProjIds.SilkShotCharged, SilkShotProjCharged.rpcInvoke },
		{ (int)ProjIds.SpinWheel, SpinWheelProj.rpcInvoke },
		{ (int)ProjIds.SpinWheelChargedStart, SpinWheelProjChargedStart.rpcInvoke },
		{ (int)ProjIds.SpinWheelCharged, SpinWheelProjCharged.rpcInvoke },
		{ (int)ProjIds.SonicSlicerStart, SonicSlicerStart.rpcInvoke },
		{ (int)ProjIds.SonicSlicer, SonicSlicerProj.rpcInvoke },
		{ (int)ProjIds.SonicSlicerCharged, SonicSlicerProjCharged.rpcInvoke },
		{ (int)ProjIds.StrikeChain, StrikeChainProj.rpcInvoke },
		{ (int)ProjIds.StrikeChainCharged, StrikeChainProjCharged.rpcInvoke },
		{ (int)ProjIds.MagnetMine, MagnetMineProj.rpcInvoke },
		{ (int)ProjIds.MagnetMineCharged, MagnetMineProjCharged.rpcInvoke },
		{ (int)ProjIds.SpeedBurner, SpeedBurnerProj.rpcInvoke },
		{ (int)ProjIds.SpeedBurnerWater, SpeedBurnerProjWater.rpcInvoke },
		{ (int)ProjIds.SpeedBurnerTrail, SpeedBurnerProjGround.rpcInvoke },
		{ (int)ProjIds.ItemTracer, ItemTracerProj.rpcInvoke },
		{ (int)ProjIds.GigaCrush, GigaCrushProj.rpcInvoke },


		//X3 PROJS
		{ (int)ProjIds.AcidBurst, AcidBurstProj.rpcInvoke },
		{ (int)ProjIds.AcidBurstSmall, AcidBurstProjSmall.rpcInvoke },
		{ (int)ProjIds.AcidBurstCharged, AcidBurstProjCharged.rpcInvoke },
		{ (int)ProjIds.ParasiticBomb, ParasiticBombProj.rpcInvoke },
		{ (int)ProjIds.ParasiticBombCharged, ParasiticBombProjCharged.rpcInvoke },
		{ (int)ProjIds.TriadThunder, TriadThunderProj.rpcInvoke },
		{ (int)ProjIds.TriadThunderQuake, TriadThunderQuake.rpcInvoke },
		{ (int)ProjIds.TriadThunderCharged, TriadThunderProjCharged.rpcInvoke },
		{ (int)ProjIds.TriadThunderBeam, TriadThunderBeamPiece.rpcInvoke },
		{ (int)ProjIds.TriadThunderBall, TriadThunderBall.rpcInvoke },
		{ (int)ProjIds.SpinningBlade, SpinningBladeProj.rpcInvoke },
		{ (int)ProjIds.SpinningBladeCharged, SpinningBladeProjCharged.rpcInvoke },
		{ (int)ProjIds.RaySplasher, RaySplasherProj.rpcInvoke },
		{ (int)ProjIds.RaySplasherChargedProj, RaySplasherTurretProj.rpcInvoke },
		{ (int)ProjIds.GravityWell, GravityWellProj.rpcInvoke },
		{ (int)ProjIds.GravityWellCharged, GravityWellProjCharged.rpcInvoke },
		{ (int)ProjIds.FrostShield, FrostShieldProj.rpcInvoke },
		{ (int)ProjIds.FrostShieldAir, FrostShieldProjAir.rpcInvoke },
		{ (int)ProjIds.FrostShieldGround, FrostShieldProjGround.rpcInvoke },
		{ (int)ProjIds.FrostShieldCharged, FrostShieldProjCharged.rpcInvoke },
		{ (int)ProjIds.FrostShieldChargedGrounded, FrostShieldProjChargedGround.rpcInvoke },
		{ (int)ProjIds.FrostShieldPlatform, FrostShieldProjPlatform.rpcInvoke },
		{ (int)ProjIds.TornadoFang, TornadoFangProj.rpcInvoke },
		{ (int)ProjIds.TornadoFang2, TornadoFangProj.rpcInvoke },
		{ (int)ProjIds.TornadoFangCharged, TornadoFangProjCharged.rpcInvoke },
		{ (int)ProjIds.XSaberProj, XSaberProj.rpcInvoke },

		//EXTRA
		{ (int)ProjIds.UPParryMelee, UPParryMeleeProj.rpcInvoke },
		{ (int)ProjIds.UPParryProj, UPParryRangedProj.rpcInvoke },
		
		// Vile
		{ (int)ProjIds.FrontRunner, VileCannonProj.rpcInvoke },
		{ (int)ProjIds.FatBoy, VileCannonProj.rpcInvoke },
		{ (int)ProjIds.LongshotGizmo, VileCannonProj.rpcInvoke },
		{ (int)ProjIds.RocketPunch, RocketPunchProj.rpcInvoke },
		{ (int)ProjIds.SpoiledBrat, RocketPunchProj.rpcInvoke },
		{ (int)ProjIds.InfinityGig, RocketPunchProj.rpcInvoke },
		{ (int)ProjIds.VileMissile, VileMissileProj.rpcInvoke },
		{ (int)ProjIds.PopcornDemon, VileMissileProj.rpcInvoke },
		{ (int)ProjIds.PopcornDemonSplit, VileMissileProj.rpcInvoke },
		{ (int)ProjIds.ElectricShock, StunShotProj.rpcInvoke },
		{ (int)ProjIds.SpreadShot, StunShotProj2.rpcInvoke },
		{ (int)ProjIds.MK2StunShot, VileMK2StunShotProj.rpcInvoke },
		{ (int)ProjIds.RumblingBangGrenade, NapalmGrenadeProj.rpcInvoke },
		{ (int)ProjIds.RumblingBangProj, NapalmPartProj.rpcInvoke },
		{ (int)ProjIds.FlameRoundGrenade, MK2NapalmGrenadeProj.rpcInvoke },
		{ (int)ProjIds.FlameRoundProj, MK2NapalmProj.rpcInvoke },
		{ (int)ProjIds.FlameRoundFlameProj, MK2NapalmFlame.rpcInvoke },
		{ (int)ProjIds.FlameRoundWallProj, MK2NapalmWallProj.rpcInvoke },
		{ (int)ProjIds.SplashHitGrenade, SplashHitGrenadeProj.rpcInvoke },
		{ (int)ProjIds.SplashHitProj, SplashHitProj.rpcInvoke },
		{ (int)ProjIds.VileBomb, VileBombProj.rpcInvoke },
		{ (int)ProjIds.VileBombSplit, VileBombSplitProj.rpcInvoke },
		{ (int)ProjIds.PeaceOutRoller, PeaceOutRollerProj.rpcInvoke },
		{ (int)ProjIds.PeaceOutRollerSplit, PeaceOutRollerSplitProj.rpcInvoke },
		{ (int)ProjIds.ParasiteSword, VileParasiteSword.rpcInvoke },
		{ (int)ProjIds.MaroonedTomahawk, VileMaroonedTomahawk.rpcInvoke },
		{ (int)ProjIds.QuickHomesick, VileQuickHomesick.rpcInvoke },
		{ (int)ProjIds.WildHorseKick, FlamethrowerWildHorseKick.rpcInvoke },
		{ (int)ProjIds.DragonsWrath, FlamethrowerDragonsWrath.rpcInvoke },
		{ (int)ProjIds.SeaDragonRage, FlamethrowerSeaDragonRage.rpcInvoke },
		{ (int)ProjIds.StraightNightmare, StraightNightmareProj.rpcInvoke },
		{ (int)ProjIds.RisingSpecter, RisingSpecterProj.rpcInvoke },
		{ (int)ProjIds.NecroBurst, NecroBurstProj.rpcInvoke },
		{ (int)ProjIds.NecroBurstShrapnel, RAShrapnelProj.rpcInvoke },
		{ (int)ProjIds.Vulcan, VulcanCherryBlast.rpcInvoke },
		{ (int)ProjIds.DistanceNeedler, VulcanDistanceNeedler.rpcInvoke },
		{ (int)ProjIds.BuckshotDance, VulcanBuckshotDance.rpcInvoke },
		{ (int)ProjIds.HexaInvolute, HexaInvoluteProj.rpcInvoke },

		// Zero
		{ (int)ProjIds.SuiretsusanProj, SuiretsusenProj.rpcInvoke },
		{ (int)ProjIds.TBreakerProj, TBreakerProj.rpcInvoke },
		{ (int)ProjIds.ZSaberProj, ZSaberProj.rpcInvoke },
		{ (int)ProjIds.Gemnu, GenmuProj.rpcInvoke },
		{ (int)ProjIds.Shingetsurin, ShingetsurinProj.rpcInvoke },
		{ (int)ProjIds.ZBuster2, ZBuster2Proj.rpcInvoke },
		{ (int)ProjIds.ZBuster3, ZBuster3Proj.rpcInvoke },
		{ (int)ProjIds.ZBuster4, ZBuster4Proj.rpcInvoke },
		{ (int)ProjIds.FSplasher, FSplasherProj.rpcInvoke },
		{ (int)ProjIds.CFlasher, RakuhouhaProj.rpcInvoke },
		{ (int)ProjIds.Rakuhouha, RakuhouhaProj.rpcInvoke },
		{ (int)ProjIds.Rekkoha, RekkohaProj.rpcInvoke },
		{ (int)ProjIds.ShinMessenkou, ShinMessenkouProj.rpcInvoke },
		{ (int)ProjIds.DarkHold, DarkHoldProj.rpcInvoke },
		{ (int)ProjIds.QuakeBlazer, DanchienExplosionProj.rpcInvoke },
		{ (int)ProjIds.QuakeBlazerFlame, QuakeBlazerFlamePart.rpcInvoke },

		//Punchy Zero
		{ (int)ProjIds.PZeroHadangeki, PZeroHadangeki.rpcInvoke },

		// Buster Zero
		{ (int)ProjIds.DZBuster, DZBusterProj.rpcInvoke },
		{ (int)ProjIds.DZBuster2, DZBuster2Proj.rpcInvoke },
		{ (int)ProjIds.DZBuster3, DZBuster3Proj.rpcInvoke },
		{ (int)ProjIds.DZHadangeki, DZHadangekiProj.rpcInvoke },

		//Sigma	
		{ (int)ProjIds.SigmaSlash, SigmaSlashProj.rpcInvoke },
		{ (int)ProjIds.SigmaBall, SigmaBallProj.rpcInvoke },
		{ (int)ProjIds.Sigma2Ball, SigmaElectricBallProj.rpcInvoke },
		{ (int)ProjIds.Sigma2Ball2, SigmaElectricBall2Proj.rpcInvoke },
		{ (int)ProjIds.SigmaWolfHeadBallProj, WolfSigmaBall.rpcInvoke },
		{ (int)ProjIds.SigmaWolfHeadFlameProj, WolfSigmaFlame.rpcInvoke },
		{ (int)ProjIds.Sigma3KaiserBeam, KaiserSigmaBeamProj.rpcInvoke },
		{ (int)ProjIds.Sigma3KaiserMissile, KaiserSigmaMissileProj.rpcInvoke },
		{ (int)ProjIds.Sigma3KaiserMine, KaiserSigmaMineProj.rpcInvoke },
		
		// Mavericks
		{ (int)ProjIds.ChillPIceBlow, ShotgunIceProjCharged.rpcInvoke },
		{ (int)ProjIds.ChillPIceShot, ChillPIceProj.rpcInvoke },
		{ (int)ProjIds.ChillPIcePenguin, ChillPIceStatueProj.rpcInvoke },
		{ (int)ProjIds.ChillPBlizzard, ChillPBlizzardProj.rpcInvoke },
		{ (int)ProjIds.SparkMSpark, TriadThunderProjCharged.rpcInvoke },
		{ (int)ProjIds.ArmoredAChargeRelease, ArmoredAChargeReleaseProj.rpcInvoke },
		{ (int)ProjIds.ArmoredAProj, ArmoredAProj.rpcInvoke },
		{ (int)ProjIds.LaunchOMissle, LaunchOMissile.rpcInvoke },
		{ (int)ProjIds.LaunchOWhirlpool, LaunchOWhirlpoolProj.rpcInvoke },
		{ (int)ProjIds.LaunchOTorpedo, TorpedoProjChargedOcto.rpcInvoke },	
		{ (int)ProjIds.BoomerangKBoomerang, BoomerangKBoomerangProj.rpcInvoke },
		{ (int)ProjIds.StingCSting, StingCStingProj.rpcInvoke },
		{ (int)ProjIds.StingCSpike, StingCSpikeProj.rpcInvoke },
		{ (int)ProjIds.StormEBird, StormEBirdProj.rpcInvoke },
		{ (int)ProjIds.StormEGust, StormEGustProj.rpcInvoke },
		{ (int)ProjIds.StormEEgg, StormEEggProj.rpcInvoke },
		{ (int)ProjIds.StormETornado, TornadoProj.rpcInvoke },
		{ (int)ProjIds.FlameMFireball, FlameMFireballProj.rpcInvoke },
		{ (int)ProjIds.FlameMOil, FlameMOilProj.rpcInvoke },
		{ (int)ProjIds.FlameMOilSpill, FlameMOilSpillProj.rpcInvoke },
		{ (int)ProjIds.FlameMOilFire, FlameMBigFireProj.rpcInvoke },
		{ (int)ProjIds.FlameMStompShockwave, FlameMStompShockwave.rpcInvoke },
		{ (int)ProjIds.VelGFire, VelGFireProj.rpcInvoke },
		{ (int)ProjIds.VelGIce, VelGIceProj.rpcInvoke },
		{ (int)ProjIds.WSpongeChain, WSpongeSideChainProj.rpcInvoke },
		{ (int)ProjIds.WSpongeUpChain, WSpongeUpChainProj.rpcInvoke },
		{ (int)ProjIds.WSpongeChainSpin, WSpongeChainSpinProj.rpcInvoke },
		{ (int)ProjIds.WSpongeSeed, WSpongeSeedProj.rpcInvoke },
		{ (int)ProjIds.WSpongeSeedAI, WSpongeSeedProjAI.rpcInvoke },
		{ (int)ProjIds.WSpongeSeedAIStriker, WSpongeSeedProjAIStriker.rpcInvoke },
		{ (int)ProjIds.WSpongeSpike, WSpongeSpike.rpcInvoke },
		{ (int)ProjIds.WheelGSpinWheel, WheelGSpinWheelProj.rpcInvoke },
		{ (int)ProjIds.WheelGSpit, WheelGSpitProj.rpcInvoke },
		{ (int)ProjIds.BCrabBubbleSplash, BCrabBubbleSplashProj.rpcInvoke },
		{ (int)ProjIds.BCrabBubbleShield, BCrabShieldProj.rpcInvoke },
		{ (int)ProjIds.BCrabCrablingBubble, BCrabSummonBubbleProj.rpcInvoke },
		{ (int)ProjIds.FStagFireball, FStagFireballProj.rpcInvoke },
		{ (int)ProjIds.FStagDashTrail, FStagTrailProj.rpcInvoke },
		{ (int)ProjIds.FStagDashCharge, FStagDashChargeProj.rpcInvoke },
		{ (int)ProjIds.FStagDash, FStagDashProj.rpcInvoke },
		{ (int)ProjIds.MorphMCThread, MorphMCThreadProj.rpcInvoke },
		{ (int)ProjIds.MorphMPowder, MorphMPowderProj.rpcInvoke },
		{ (int)ProjIds.MagnaCMagnetPull, MagnaCMagnetPullProj.rpcInvoke },
		{ (int)ProjIds.CSnailCrystalHunter, CSnailCrystalHunterProj.rpcInvoke },
		{ (int)ProjIds.OverdriveOSonicSlicer, OverdriveOSonicSlicerProj.rpcInvoke },
		{ (int)ProjIds.OverdriveOSonicSlicerUp, OverdriveOSonicSlicerUpProj.rpcInvoke },
		{ (int)ProjIds.FakeZeroBuster, FakeZeroBusterProj.rpcInvoke },
		{ (int)ProjIds.FakeZeroBuster2, FakeZeroBuster2Proj.rpcInvoke },
		{ (int)ProjIds.FakeZeroBuster3, FakeZeroBusterProj3.rpcInvoke },
		{ (int)ProjIds.FakeZeroSwordBeam, FakeZeroSwordBeamProj.rpcInvoke },
		{ (int)ProjIds.FakeZeroMelee, FakeZeroMeleeProj.rpcInvoke },
		{ (int)ProjIds.FakeZeroGroundPunch, FakeZeroRockProj.rpcInvoke },
		{ (int)ProjIds.TSeahorseAcid2, TSeahorseAcid2Proj.rpcInvoke },
		{ (int)ProjIds.TSeahorseAcid1, AcidBurstProjSmall.rpcInvoke },	
		{ (int)ProjIds.TSeahorseAcid3, TSeahorseAcidProj.rpcInvoke },	
		{ (int)ProjIds.TunnelRTornadoFang, TunnelRTornadoFang.rpcInvoke },	
		{ (int)ProjIds.TunnelRTornadoFang2, TunnelRTornadoFang.rpcInvoke },	
		{ (int)ProjIds.TunnelRTornadoFangDiag, TunnelRTornadoFangDiag.rpcInvoke },
		{ (int)ProjIds.VoltCBall, TriadThunderProjCharged.rpcInvoke },
		{ (int)ProjIds.VoltCTriadThunder, VoltCTriadThunderProj.rpcInvoke },
		{ (int)ProjIds.VoltCSuck, VoltCSuckProj.rpcInvoke },
		{ (int)ProjIds.VoltCUpBeam2, VoltCUpBeamProj.rpcInvoke },
		{ (int)ProjIds.VoltCUpBeam, VoltCUpBeamProj.rpcInvoke },
		{ (int)ProjIds.VoltCCharge, VoltCChargeProj.rpcInvoke },
		{ (int)ProjIds.VoltCBarrier, VoltCBarrierProj.rpcInvoke },
		{ (int)ProjIds.VoltCSparkle, VoltCSparkleProj.rpcInvoke },
		{ (int)ProjIds.CrushCProj, CrushCProj.rpcInvoke },
		{ (int)ProjIds.CrushCArmProj, CrushCArmProj.rpcInvoke },
		{ (int)ProjIds.NeonTRaySplasher, NeonTRaySplasherProj.rpcInvoke },
		{ (int)ProjIds.GBeetleBall, GBeetleBallProj.rpcInvoke },
		{ (int)ProjIds.GBeetleGravityWell, GBeetleGravityWellProj.rpcInvoke },
		{ (int)ProjIds.DrDopplerBall, DrDopplerBallProj.rpcInvoke },
		{ (int)ProjIds.DrDopplerBall2, DrDopplerBallProj.rpcInvoke },
		{ (int)ProjIds.BHornetHomingBee, BHornetHomingBeeProj.rpcInvoke },
		{ (int)ProjIds.BHornetBee, BHornetBeeProj.rpcInvoke },
		{ (int)ProjIds.BHornetCursor, BHornetCursorProj.rpcInvoke },
		{ (int)ProjIds.BBuffaloIceProj, BBuffaloIceProj.rpcInvoke },
		{ (int)ProjIds.BBuffaloIceProjGround, BBuffaloIceProjGround.rpcInvoke },
		{ (int)ProjIds.BBuffaloBeam, BBuffaloBeamProj.rpcInvoke },
		{ (int)ProjIds.BBuffaloCrash, BBuffaloCrashProj.rpcInvoke },
		{ (int)ProjIds.BBuffaloIceProjAI, BBuffaloIceProjAI.rpcInvoke },
		{ (int)ProjIds.BBuffaloIceProjAIStriker, BBuffaloIceProjAIStriker.rpcInvoke },


		// Axl
		{ (int)ProjIds.BlackArrowGround, BlackArrowGrounded.rpcInvoke },
		{ (int)ProjIds.AssassinBulletEX, AssassinationProj.rpcInvoke },
		// Rides
		{ (int)ProjIds.MechTorpedo, TorpedoProjMech.rpcInvoke },

	};

}

public struct ProjParameters {
	public int projId;
	public Point pos;
	public int xDir;
	public Player player;
	public ushort netId;
	public byte[] extraData;
	public float angle;
	public float byteAngle;
	public Actor owner;
}

public delegate Projectile ProjCreate(ProjParameters arg);
